#server:
#  port: 9091
#
#eureka:
#  client:
#    service-url:
#      defaultZone: http://localhost:8761/eureka/
#spring:
#  application:
#    name: RESTAURANT-SERVICE
#  datasource:
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://localhost:3306/restaurantdb
#    username: root
#    password: root
#  jpa:
#    hibernate:
#      ddl-auto: update
#    show-sql: true

server:
  port: 9091

spring:
  profiles:
    active: dev

  application:
    name: RESTAURANT-SERVICE
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect