#server:
#  port: 9094
#
#eureka:
#  client:
#    service-url:
#      defaultZone: http://localhost:8761/eureka/
#
#Spring:
#  application:
#    name: ORDERSERVICE
#
#  data:
#    mongodb:
#      url: mongodb://localhost:27017/orderdb
#      host: localhost
#      port: 27017
#      database: orderdb
#      repositories:
#        enabled: true

server:
  port: 9094

spring:
  profiles:
    active: dev
  application:
    name: ORDER-SERVICE

